### ISSUE TITLE
 关于vyos登录账号的问题(无管理账号vyos)

### ISSUE THREAD

**Issue by jack20230322** [BurlyLuo/clab#1]
按照罗老师提供的CALB实验，部署clab后，使用docker exec -it clab-bgp-cplane-demo-leaf0 bash (包括 spine0 、leaf1、spine1).
通过   su vyos命令切换到vyos 管理账号。都报错：不存在此用户。
root@kind1:~# docker exec -it  clab-bgp-cplane-demo-leaf0 bash
root@leaf0:/# su vyos
Unknown id: vyos

如何解决？谢谢。

**Comment by BurlyLuo** [comment]
在ubuntu22.04以上的环境上，此时vyos1.2.8的此时便有此问题，建议使用更高版本的vyos。
可采用我最近新编的vyos1.4.x的版本：
```
docker pull burlyluo/vyos:1.4.0
```
